### ISSUE TITLE
Missing some necessary lib files for building from source code

### ISSUE THREAD

**Issue by leelele-cug** [nini-lxz/NonLocalLowRankMeshDenoise#2]
When I try to build it from source code, some error occurs:

- In Debug mode:

`1>LINK : fatal error LNK1104: 无法打开文件“../LinearSolver/LinearSolverLib_D.lib”`

- In Release mode:

`1>LINK : fatal error LNK1104: 无法打开文件“../LinearSolver/LinearSolverLib_R.lib”`

My enviroment settings:
```
-Win10
-VS2010
```

**Comment by nini-lxz** [comment]
Thanks for your reminder! I have uploaded the two missed lib files under the LinearSolver folder.

**Comment by leelele-cug** [comment]
OK. Thanks.
